//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_NATURE_CURRENCY
    {
        public Nullable<bool> CNIC_VERIFIED { get; set; }
        public Nullable<System.DateTime> ACCOUNT_ENTRY_DATE { get; set; }
        public Nullable<int> GL_CODE { get; set; }
        public Nullable<int> SL_CODE { get; set; }
        public Nullable<int> ACCOUNT_TYPE { get; set; }
        public Nullable<int> CURRENCY { get; set; }
        public string ACCOUNT_NUMBER { get; set; }
        public string ACCOUNT_TITLE { get; set; }
        public string INITIAL_DEPOSIT { get; set; }
        public Nullable<bool> ACCOUNT_MODE { get; set; }
        public Nullable<bool> MINOR_ACCOUNT { get; set; }
        public int ID { get; set; }
        public Nullable<int> ACCOUNT_OPEN_TYPE { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public string PROFILE_ACCOUNT_NO { get; set; }
        public Nullable<int> ACCOUNT_MODE_DETAIL { get; set; }
        public string PROFILE_STATUS { get; set; }
        public Nullable<System.DateTime> PROFILE_CREATION_DATE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string IBAN { get; set; }
    }
}
