//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_AUTHORIZED_PERSONS
    {
        public int ID { get; set; }
        public Nullable<int> BI_ID { get; set; }
        public string CIF_NO { get; set; }
        public string NAME { get; set; }
        public string CNIC { get; set; }
        public Nullable<bool> APPLICANT_IN_NEGATIVE_LIST { get; set; }
        public Nullable<bool> POWER_OF_ATTORNY { get; set; }
        public Nullable<bool> SIGNATURE_AUTHORITY { get; set; }
        public string APPLICANT_STATUS { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    }
}
