//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS_INFORMATION
    {
        public int ID { get; set; }
        public Nullable<int> BI_ID { get; set; }
        public Nullable<int> COUNTRY { get; set; }
        public Nullable<int> CITY { get; set; }
        public string BUILDING_SUITE { get; set; }
        public string STREET { get; set; }
        public string FLOOR { get; set; }
        public string DISTRICT { get; set; }
        public string PO_BOX { get; set; }
        public string POSTAL_CODE { get; set; }
        public string TEL_OFFICE { get; set; }
        public string TEL_RESIDENCE { get; set; }
        public string MOBILE_NO { get; set; }
        public string FAX_NO { get; set; }
        public Nullable<int> SMS_ALERT_REQUIRED { get; set; }
        public Nullable<bool> EMAIL { get; set; }
        public Nullable<System.DateTime> UPDATED_TIME { get; set; }
        public Nullable<int> PROVINCE { get; set; }
    }
}
