//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT_INFORMATION_CIFS
    {
        public int ID { get; set; }
        public int BI_ID { get; set; }
        public string CUSTOMER_CIF_NO { get; set; }
        public int IS_PRIMARY_ACCOUNT_HOLDER { get; set; }
        public int POWER_OF_ATTORNY { get; set; }
        public int SIGNATURE_AUTHORITY { get; set; }
        public string INVESTMENT_SHARE { get; set; }
        public string APPLICANT_STATUS { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_IDENTITY { get; set; }
    }
}
