//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT_INFORMATION
    {
        public int ID { get; set; }
        public Nullable<int> BI_ID { get; set; }
        public string CUSTOMER_CIF_NO { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_CNIC { get; set; }
        public Nullable<int> IS_PRIMARY_ACCOUNT_HOLDER { get; set; }
        public Nullable<int> ACCOUNT_IN_NEGATIVE_LIST { get; set; }
        public Nullable<int> POWER_OF_ATTORNY { get; set; }
        public Nullable<int> SIGNATURE_AUTHORITY { get; set; }
        public Nullable<int> APPLICANT_STATUS { get; set; }
        public Nullable<int> RELATIONSHIP_NOT_PRIMARY { get; set; }
        public string RELATIONSHIP_DETAIL { get; set; }
        public string INVESTMENT_SHARE { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    }
}
