//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANKING_RELATIONSHPS
    {
        public int ID { get; set; }
        public Nullable<int> BI_ID { get; set; }
        public Nullable<int> NBP_BRANCH_INFORMATION { get; set; }
        public Nullable<int> NBP_ACCOUNT_TYPE { get; set; }
        public string NBP_ACCOUNT_NUMBER { get; set; }
        public string NBP_ACCOUNT_TITLE { get; set; }
        public string NBP_RELATIONSHIP_SINCE { get; set; }
        public Nullable<int> OTHER_BANK_CODE { get; set; }
        public string OTHER_BRANCH_NAME { get; set; }
        public string OTHER_ACCOUNT_NUMBER { get; set; }
        public string OTHER_ACCOUNT_TITLE { get; set; }
        public string OTHER_RELATIONSHIP_SINCE { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    }
}
