//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASIC_INFORMATIONS
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CIF_ENTRY_DATE { get; set; }
        public Nullable<int> CIF_TYPE { get; set; }
        public Nullable<int> DOCUMENT_TYPE_PRIMARY { get; set; }
        public string CNIC { get; set; }
        public Nullable<int> TITLE { get; set; }
        public string NAME { get; set; }
        public Nullable<int> TITLE_FH { get; set; }
        public string NAME_FH { get; set; }
        public string CNIC_FH { get; set; }
        public string CIF_FH { get; set; }
        public string NAME_MOTHER { get; set; }
        public string CNIC_MOTHER { get; set; }
        public string CNIC_MOTHER_OLD { get; set; }
        public string DOB { get; set; }
        public string POB { get; set; }
        public Nullable<int> COB { get; set; }
        public Nullable<int> MARTIAL_STATUS { get; set; }
        public Nullable<int> GENDER { get; set; }
        public Nullable<int> RELIGION { get; set; }
        public Nullable<int> RESIDENT_TYPE { get; set; }
        public string MONTHLY_INCOME { get; set; }
        public Nullable<int> COUNTRY_RESIDENCE { get; set; }
        public Nullable<int> COSTUMER_DEAL { get; set; }
        public string NAME_OFFICE { get; set; }
        public string SALES_TAX_NO { get; set; }
        public string NTN { get; set; }
        public Nullable<int> ISSUING_AGENCY { get; set; }
        public string REG_NO { get; set; }
        public string REG_DATE { get; set; }
        public string COMMENCEMENT_DATE { get; set; }
        public string PAST_BUSS_EXP { get; set; }
        public Nullable<int> ACCOUNT_NATURE { get; set; }
        public Nullable<int> CUSTOMER_CLASSIFICATION { get; set; }
        public string CIF_GROUP { get; set; }
        public Nullable<int> NATURE_BUSINESS { get; set; }
        public string NATURE_BUSINESS_DESCRP { get; set; }
        public Nullable<int> CATERGORY_NBP { get; set; }
        public Nullable<int> CATERGORY_SBP { get; set; }
        public Nullable<int> CATERGORY_BASE { get; set; }
        public string SHARE { get; set; }
        public Nullable<int> APPLICANT_STATUS { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> SHARE_HOLDER_FILLED { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
        public Nullable<int> COUNTRY_INCORPORATION { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public Nullable<int> BUSINESS_TYPE { get; set; }
        public Nullable<int> INSTITUTION_TYPE { get; set; }
        public Nullable<int> SIC_CODE { get; set; }
        public Nullable<int> SUB_INDUSTRY { get; set; }
        public Nullable<bool> DOCUMENT_VERIFIED { get; set; }
        public string RISK_CATEGORY { get; set; }
        public string RISK_SCORE { get; set; }
        public string PROFILE_CIF_NO { get; set; }
        public string PROFILE_STATUS { get; set; }
        public Nullable<System.DateTime> PROFILE_CREATION_DATE { get; set; }
        public string BRANCH_CODE { get; set; }
        public Nullable<int> CUSTOMER_TYPE { get; set; }
        public Nullable<int> GOV_TYPE { get; set; }
        public string WHO_NAME { get; set; }
        public string WHO_DESIG { get; set; }
    }
}
