//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class CAOPDbContext : DbContext
    {
       
    
        public virtual DbSet<ACCOMODATION_TYPES> ACCOMODATION_TYPES { get; set; }
        public virtual DbSet<ACCOUNT_AUTHORIZED_PERSONS> ACCOUNT_AUTHORIZED_PERSONS { get; set; }
        public virtual DbSet<ACCOUNT_CLASS> ACCOUNT_CLASS { get; set; }
        public virtual DbSet<ACCOUNT_CONTACT_INFO> ACCOUNT_CONTACT_INFO { get; set; }
        public virtual DbSet<ACCOUNT_DELTE_LOG> ACCOUNT_DELTE_LOG { get; set; }
        public virtual DbSet<ACCOUNT_GROUP> ACCOUNT_GROUP { get; set; }
        public virtual DbSet<ACCOUNT_NATURE_CURRENCY> ACCOUNT_NATURE_CURRENCY { get; set; }
        public virtual DbSet<ACCOUNT_OPEN_TYPE> ACCOUNT_OPEN_TYPE { get; set; }
        public virtual DbSet<ACCOUNT_REVIEW> ACCOUNT_REVIEW { get; set; }
        public virtual DbSet<ACCOUNT_STATEMENT_FREQUENCY> ACCOUNT_STATEMENT_FREQUENCY { get; set; }
        public virtual DbSet<ADDRESS_INFORMATION> ADDRESS_INFORMATION { get; set; }
        public virtual DbSet<ADDRESS_VERIFIED> ADDRESS_VERIFIED { get; set; }
        public virtual DbSet<APPLICANT_INFORMATION> APPLICANT_INFORMATION { get; set; }
        public virtual DbSet<APPLICANT_INFORMATION_CIFS> APPLICANT_INFORMATION_CIFS { get; set; }
        public virtual DbSet<APPLICANT_STATUSES> APPLICANT_STATUSES { get; set; }
        public virtual DbSet<APPLICANT_STATUSES_BUSINESS> APPLICANT_STATUSES_BUSINESS { get; set; }
        public virtual DbSet<ARMY_RANK_CODES> ARMY_RANK_CODES { get; set; }
        public virtual DbSet<AUTHORITY_TO_OPERATE> AUTHORITY_TO_OPERATE { get; set; }
        public virtual DbSet<AVERAGE_CASH_DEPOSITS> AVERAGE_CASH_DEPOSITS { get; set; }
        public virtual DbSet<AVERAGE_NON_CASH_DEPOSITS> AVERAGE_NON_CASH_DEPOSITS { get; set; }
        public virtual DbSet<BANKING_RELATIONSHPS> BANKING_RELATIONSHPS { get; set; }
        public virtual DbSet<BASE_CATEGORIES> BASE_CATEGORIES { get; set; }
        public virtual DbSet<BASIC_INFORMATIONS> BASIC_INFORMATIONS { get; set; }
        public virtual DbSet<BRANCHES> BRANCHES { get; set; }
        public virtual DbSet<BUSINESS_ACOUNTS> BUSINESS_ACOUNTS { get; set; }
        public virtual DbSet<BUSINESS_CUSTOMER_CLASSIFICATIONS> BUSINESS_CUSTOMER_CLASSIFICATIONS { get; set; }
        public virtual DbSet<BUSINESS_DETAIL> BUSINESS_DETAIL { get; set; }
        public virtual DbSet<BUSINESS_TYPE> BUSINESS_TYPE { get; set; }
        public virtual DbSet<CERTIFICATE_DEPOSIT_INFO> CERTIFICATE_DEPOSIT_INFO { get; set; }
        public virtual DbSet<CIF_REVIEW> CIF_REVIEW { get; set; }
        public virtual DbSet<CIF_TYPES> CIF_TYPES { get; set; }
        public virtual DbSet<CITIES> CITIES { get; set; }
        public virtual DbSet<CITIES_BUSINESS_DETAILS> CITIES_BUSINESS_DETAILS { get; set; }
        public virtual DbSet<CONSUMER_SEGMENTS> CONSUMER_SEGMENTS { get; set; }
        public virtual DbSet<CONTACT_INFOS> CONTACT_INFOS { get; set; }
        public virtual DbSet<COSTUMER_DEALINGS> COSTUMER_DEALINGS { get; set; }
        public virtual DbSet<COUNTRIES> COUNTRIES { get; set; }
        public virtual DbSet<COUNTRIES_BUSINESS_DETAILS> COUNTRIES_BUSINESS_DETAILS { get; set; }
        public virtual DbSet<COUNTRIES_TAX_MISCELLANEOUS_INFORMATION> COUNTRIES_TAX_MISCELLANEOUS_INFORMATION { get; set; }
        public virtual DbSet<COUNTRY_CODES> COUNTRY_CODES { get; set; }
        public virtual DbSet<CURRENCY> CURRENCY { get; set; }
        public virtual DbSet<CUSTOMER_TYPE> CUSTOMER_TYPE { get; set; }
        public virtual DbSet<Description_Documents> Description_Documents { get; set; }
        public virtual DbSet<Description_Documents_Business> Description_Documents_Business { get; set; }
        public virtual DbSet<DISTRICTS> DISTRICTS { get; set; }
        public virtual DbSet<DOCUMENT_REQUIRED> DOCUMENT_REQUIRED { get; set; }
        public virtual DbSet<DOCUMENT_TYPES> DOCUMENT_TYPES { get; set; }
        public virtual DbSet<DOCUMENT_TYPES_PRIMARY> DOCUMENT_TYPES_PRIMARY { get; set; }
        public virtual DbSet<DOCUMENTS> DOCUMENTS { get; set; }
        public virtual DbSet<DOCUMENTS_FATCA> DOCUMENTS_FATCA { get; set; }
        public virtual DbSet<E_STATEMENT_REQUIRED> E_STATEMENT_REQUIRED { get; set; }
        public virtual DbSet<EDUCATION> EDUCATION { get; set; }
        public virtual DbSet<EDUCATIONS> EDUCATIONS { get; set; }
        public virtual DbSet<EMAILS> EMAILS { get; set; }
        public virtual DbSet<EMPLOYER_CODES> EMPLOYER_CODES { get; set; }
        public virtual DbSet<EMPLOYMENT_DETAILS> EMPLOYMENT_DETAILS { get; set; }
        public virtual DbSet<FATCAS> FATCAS { get; set; }
        public virtual DbSet<FATCAS_TINS> FATCAS_TINS { get; set; }
        public virtual DbSet<FREQUENCY_GROSS_SALES> FREQUENCY_GROSS_SALES { get; set; }
        public virtual DbSet<FTCA_CLASSIFICATIONS> FTCA_CLASSIFICATIONS { get; set; }
        public virtual DbSet<FTCA_DOCUMENTATIONS> FTCA_DOCUMENTATIONS { get; set; }
        public virtual DbSet<GENDERS> GENDERS { get; set; }
        public virtual DbSet<GL_CODE> GL_CODE { get; set; }
        public virtual DbSet<GOV_CIF_TYPE> GOV_CIF_TYPE { get; set; }
        public virtual DbSet<HEAD_CONTACT_INFOS> HEAD_CONTACT_INFOS { get; set; }
        public virtual DbSet<IDENTITIES> IDENTITIES { get; set; }
        public virtual DbSet<IDENTITY_TYPES> IDENTITY_TYPES { get; set; }
        public virtual DbSet<INFO_TYPES_BDS> INFO_TYPES_BDS { get; set; }
        public virtual DbSet<INSTITUTION_TYPE> INSTITUTION_TYPE { get; set; }
        public virtual DbSet<ISSUING_AGENCY> ISSUING_AGENCY { get; set; }
        public virtual DbSet<KNOW_CUSTOMER_TRANSACTIONS_MODE> KNOW_CUSTOMER_TRANSACTIONS_MODE { get; set; }
        public virtual DbSet<KNOW_YOUR_CUSTOMER> KNOW_YOUR_CUSTOMER { get; set; }
        public virtual DbSet<KNOW_YOUR_CUSTOMER_RELATIONSHIP> KNOW_YOUR_CUSTOMER_RELATIONSHIP { get; set; }
        public virtual DbSet<KYC_BENEFICIAL_ENTITY> KYC_BENEFICIAL_ENTITY { get; set; }
        public virtual DbSet<KYC_EXPECTED_COUNTER_PARTIES> KYC_EXPECTED_COUNTER_PARTIES { get; set; }
        public virtual DbSet<KYC_GEOGRAPHIES_COUNTER_PARTIES> KYC_GEOGRAPHIES_COUNTER_PARTIES { get; set; }
        public virtual DbSet<KYC_PURPOSE_OF_AC> KYC_PURPOSE_OF_AC { get; set; }
        public virtual DbSet<KYC_SOURCE_OF_FUND> KYC_SOURCE_OF_FUND { get; set; }
        public virtual DbSet<MARTIAL_STATUSES> MARTIAL_STATUSES { get; set; }
        public virtual DbSet<MEANS_OF_VERIFICATION> MEANS_OF_VERIFICATION { get; set; }
        public virtual DbSet<MISCELLANEOUS_INFORMATIONS> MISCELLANEOUS_INFORMATIONS { get; set; }
        public virtual DbSet<MODE_OF_TRANSACTIONS> MODE_OF_TRANSACTIONS { get; set; }
        public virtual DbSet<MONTHLY_TURNOVER_CREDITS> MONTHLY_TURNOVER_CREDITS { get; set; }
        public virtual DbSet<MONTHLY_TURNOVER_DEBITS> MONTHLY_TURNOVER_DEBITS { get; set; }
        public virtual DbSet<NADRA_INFO> NADRA_INFO { get; set; }
        public virtual DbSet<NATIONALITIES_BASIC_INFORMATION> NATIONALITIES_BASIC_INFORMATION { get; set; }
        public virtual DbSet<NATURE_BUSINESS> NATURE_BUSINESS { get; set; }
        public virtual DbSet<NATURE_BUSINESS_GOV> NATURE_BUSINESS_GOV { get; set; }
        public virtual DbSet<NBP_BRANCH_INFORMATIONS> NBP_BRANCH_INFORMATIONS { get; set; }
        public virtual DbSet<NBP_CATEGORIES> NBP_CATEGORIES { get; set; }
        public virtual DbSet<NEXT_OF_KIN_INFO> NEXT_OF_KIN_INFO { get; set; }
        public virtual DbSet<OPERATING_INSTRUCTIONS> OPERATING_INSTRUCTIONS { get; set; }
        public virtual DbSet<OTHER_BANK_CODES> OTHER_BANK_CODES { get; set; }
        public virtual DbSet<PEPS> PEPS { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<PRINCIPAL_RENEWAL_OPTION> PRINCIPAL_RENEWAL_OPTION { get; set; }
        public virtual DbSet<PRODUCTS> PRODUCTS { get; set; }
        public virtual DbSet<PROFIT_PAYMENT> PROFIT_PAYMENT { get; set; }
        public virtual DbSet<PROVINCES> PROVINCES { get; set; }
        public virtual DbSet<PURPOSE_OF_ACCOUNT> PURPOSE_OF_ACCOUNT { get; set; }
        public virtual DbSet<REAL_BENEFICIARY_ACCOUNT> REAL_BENEFICIARY_ACCOUNT { get; set; }
        public virtual DbSet<REGIONS> REGIONS { get; set; }
        public virtual DbSet<RELATIONSHIP> RELATIONSHIP { get; set; }
        public virtual DbSet<RELIGIONS> RELIGIONS { get; set; }
        public virtual DbSet<RESIDENT_TYPES> RESIDENT_TYPES { get; set; }
        public virtual DbSet<ROLE_PERMISSIONS> ROLE_PERMISSIONS { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<SBP_CATEGORIES> SBP_CATEGORIES { get; set; }
        public virtual DbSet<SERVICE_CHARGES_EXEMPTED_CODE> SERVICE_CHARGES_EXEMPTED_CODE { get; set; }
        public virtual DbSet<SHAREHOLDER_INFORMATION> SHAREHOLDER_INFORMATION { get; set; }
        public virtual DbSet<SIC_CODES> SIC_CODES { get; set; }
        public virtual DbSet<SL_CODE> SL_CODE { get; set; }
        public virtual DbSet<SMS_ALERT_REQUIRED> SMS_ALERT_REQUIRED { get; set; }
        public virtual DbSet<SOURCE_OF_FUNDS> SOURCE_OF_FUNDS { get; set; }
        public virtual DbSet<SOURCE_OF_FUNDS_BUSINESS> SOURCE_OF_FUNDS_BUSINESS { get; set; }
        public virtual DbSet<STATUS_LOG> STATUS_LOG { get; set; }
        public virtual DbSet<SUB_INDUSTRY> SUB_INDUSTRY { get; set; }
        public virtual DbSet<TITLES> TITLES { get; set; }
        public virtual DbSet<TRANSACTIONS_TYPE> TRANSACTIONS_TYPE { get; set; }
        public virtual DbSet<Transportation_Types> Transportation_Types { get; set; }
        public virtual DbSet<USA_FUNDSTRANSFERS> USA_FUNDSTRANSFERS { get; set; }
        public virtual DbSet<USA_PHONE_NOS> USA_PHONE_NOS { get; set; }
        public virtual DbSet<USA_RESIDENCE_CARDS> USA_RESIDENCE_CARDS { get; set; }
        public virtual DbSet<USA_TAXID_TYPES> USA_TAXID_TYPES { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<USERS_PERMISSIONS> USERS_PERMISSIONS { get; set; }
        public virtual DbSet<USERS_ROLES> USERS_ROLES { get; set; }
        public virtual DbSet<WHO_AUTHORIZED> WHO_AUTHORIZED { get; set; }
        public virtual DbSet<ZAKAT_EXEMPTION_TYPE> ZAKAT_EXEMPTION_TYPE { get; set; }
        public virtual DbSet<CIF_CUSTOMER_TYPE> CIF_CUSTOMER_TYPE { get; set; }
        public virtual DbSet<CUSTOMER_TYPE_BUSINESS> CUSTOMER_TYPE_BUSINESS { get; set; }
        public virtual DbSet<DIRECTOR_STATUS> DIRECTOR_STATUS { get; set; }
        public virtual DbSet<EXPECTED_COUNTER_PARTIES> EXPECTED_COUNTER_PARTIES { get; set; }
        public virtual DbSet<GEOGRAPHIES_COUNTER_PARTIES> GEOGRAPHIES_COUNTER_PARTIES { get; set; }
        public virtual DbSet<PURPOSE_OF_ACCOUNT_BUSINESS> PURPOSE_OF_ACCOUNT_BUSINESS { get; set; }
        public virtual DbSet<REASON_ACCOUNT_OPENING> REASON_ACCOUNT_OPENING { get; set; }
        public virtual DbSet<ACCOUNT_MODES> ACCOUNT_MODES { get; set; }
        public virtual DbSet<EMPLOYER_CODE> EMPLOYER_CODE { get; set; }
        public virtual DbSet<EMPLOYER_GROUP> EMPLOYER_GROUP { get; set; }
        public virtual DbSet<EMPLOYER_SUB_GROUP> EMPLOYER_SUB_GROUP { get; set; }
        public virtual DbSet<ACCOUNT_TYPES> ACCOUNT_TYPES { get; set; }
        public virtual DbSet<ACCOUNT_MODES1> ACCOUNT_MODES1Set { get; set; }
        public virtual DbSet<EMPLOYER_CODE1> EMPLOYER_CODE1Set { get; set; }
        public virtual DbSet<EMPLOYER_GROUP1> EMPLOYER_GROUP1Set { get; set; }
        public virtual DbSet<EMPLOYER_SUB_GROUP1> EMPLOYER_SUB_GROUP1Set { get; set; }
        public virtual DbSet<EMPLOYMENT_INFORMATIONS> EMPLOYMENT_INFORMATIONS { get; set; }
        public virtual DbSet<ACCOUNT_DEL_LOG> ACCOUNT_DEL_LOG { get; set; }
        public virtual DbSet<CIF_DEL_LOG> CIF_DEL_LOG { get; set; }
        public virtual DbSet<OFFICE_CODES> OFFICE_CODES { get; set; }
        public virtual DbSet<ChangeLog> ChangeLog { get; set; }
        public virtual DbSet<ACCOUNT_PURPOSE> ACCOUNT_PURPOSE { get; set; }
    }
}
