//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLog
    {
        public decimal ApplyTo { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public decimal ChangedBy { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public int ID { get; set; }
    }
}
