//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIF_DEL_LOG
    {
        public int ID { get; set; }
        public string CIF_TYPE { get; set; }
        public string IDENTITY_TYPE { get; set; }
        public string IDENTITY_NO { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string OFFICE_NAME { get; set; }
        public Nullable<int> DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETE_DATETIME { get; set; }
    }
}
