//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIF_REVIEW
    {
        public int ID { get; set; }
        public int BID { get; set; }
        public string TAB { get; set; }
        public string FNAME { get; set; }
        public string FID { get; set; }
        public System.DateTime DATEC { get; set; }
        public int USERID { get; set; }
        public bool ACTIVE { get; set; }
        public string COMMENT { get; set; }
    }
}
