//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITIES_BUSINESS_DETAILS
    {
        public int ID { get; set; }
        public Nullable<int> BI_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public string CITY_NAME { get; set; }
    }
}
