//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT_INFOS
    {
        public int ID { get; set; }
        public Nullable<int> BI_ID { get; set; }
        public Nullable<int> CITY_PERMANENT { get; set; }
        public Nullable<int> CITY_PRESENT { get; set; }
        public string OFFICE_CONTACT { get; set; }
        public string RESIDENCE_CONTACT { get; set; }
        public string MOBILE_NO { get; set; }
        public string FAX_NO { get; set; }
        public string EMAIL { get; set; }
        public string WEB { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<int> COUNTRY_CODE { get; set; }
        public string STREET { get; set; }
        public string BIULDING_SUITE { get; set; }
        public string FLOOR { get; set; }
        public string DISTRICT { get; set; }
        public string POST_OFFICE { get; set; }
        public string POSTAL_CODE { get; set; }
        public Nullable<int> COUNTRY_CODE_PRE { get; set; }
        public string STREET_PRE { get; set; }
        public string BIULDING_SUITE_PRE { get; set; }
        public string FLOOR_PRE { get; set; }
        public string DISTRICT_PRE { get; set; }
        public string POST_OFFICE_PRE { get; set; }
        public string POSTAL_CODE_PRE { get; set; }
        public Nullable<int> PROVINCE { get; set; }
        public Nullable<int> PROVINCE_PRE { get; set; }
        public string CP_NAME { get; set; }
        public string CP_DESIGNATION { get; set; }
        public string CP_CNIC { get; set; }
        public string CP_CNIC_EXPIRY { get; set; }
        public string CP_NTN { get; set; }
    }
}
