//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEAD_CONTACT_INFOS
    {
        public int ID { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> DISTRICT { get; set; }
        public string POBOX { get; set; }
        public Nullable<int> CITY { get; set; }
        public string POSTAL_CODE { get; set; }
        public Nullable<int> COUNTRY { get; set; }
        public string PHONE_OFFICE { get; set; }
        public string MOBILE_NO { get; set; }
        public string FAX_NO { get; set; }
        public string EMAIL { get; set; }
        public string WEB { get; set; }
        public Nullable<int> BI_ID { get; set; }
        public Nullable<System.DateTime> UPDATED_TIME { get; set; }
        public Nullable<int> COUNTRY_CODE { get; set; }
        public string BIULDING_SUITE { get; set; }
        public string STREET { get; set; }
        public string FLOOR { get; set; }
        public string DISTRICT_HEAD { get; set; }
        public Nullable<int> COUNTRY_CODE_REG { get; set; }
        public string BIULDING_SUITE_REG { get; set; }
        public string STREET_REG { get; set; }
        public string FLOOR_REG { get; set; }
        public string DISTRICT_REG { get; set; }
        public string POBOX_REG { get; set; }
        public string POSTAL_REG_CODE { get; set; }
        public Nullable<int> CITY_REG { get; set; }
        public Nullable<int> PROVINCE { get; set; }
        public Nullable<int> PROVINCE_REG { get; set; }
    }
}
