//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDENTITIES
    {
        public int ID { get; set; }
        public Nullable<int> BI_ID { get; set; }
        public string CNIC_DATE_ISSUE { get; set; }
        public string EXPIRY_DATE { get; set; }
        public string IDENTIFICATION_MARK { get; set; }
        public string FAMILY_NO { get; set; }
        public string TOKEN_NO { get; set; }
        public Nullable<System.DateTime> TOKEN_ISSUE_DATE { get; set; }
        public string NTN { get; set; }
        public string NIC_OLD { get; set; }
        public Nullable<int> IDENTITY_TYPE { get; set; }
        public string IDENTITY_NO { get; set; }
        public Nullable<int> COUNTRY_ISSUE { get; set; }
        public string OTHER_IDENTITY_ISSUE_DATE { get; set; }
        public string PLACE_ISSUE { get; set; }
        public string OTHER_IDENTITY_EXPIRY_DATE { get; set; }
        public Nullable<System.DateTime> UPDATED_TIME { get; set; }
        public Nullable<int> COUNTRY_ISSUE_CNIC { get; set; }
        public string PLACE_ISSUE_CNIC { get; set; }
    }
}
