//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNOW_YOUR_CUSTOMER
    {
        public int ID { get; set; }
        public Nullable<int> BI_ID { get; set; }
        public Nullable<int> CUSTOMER_TYPE { get; set; }
        public string DESCRIPTION_IF_REFFERED { get; set; }
        public Nullable<int> EDUCATION { get; set; }
        public Nullable<int> PURPOSE_OF_ACCOUNT { get; set; }
        public string DESCRIPTION_IF_OTHER { get; set; }
        public Nullable<int> SOURCE_OF_FUNDS { get; set; }
        public string DESCRIPTION_OF_SOURCE { get; set; }
        public Nullable<bool> SERVICE_CHARGES_EXEMPTED { get; set; }
        public Nullable<int> SERVICE_CHARGES_EXEMPTED_CODE { get; set; }
        public string REASON_IF_EXEMPTED { get; set; }
        public string EXPECTED_MONTHLY_INCOME { get; set; }
        public Nullable<bool> MODE_OF_TRANSACTIONS { get; set; }
        public string OTHER_MODE_OF_TRANSACTIONS { get; set; }
        public string MAX_TRANS_AMOUNT_DR { get; set; }
        public string MAX_TRANS_AMOUNT_CR { get; set; }
        public Nullable<int> RELATIONSHIP_MANAGER { get; set; }
        public Nullable<bool> OCCUPATION_VERIFIED { get; set; }
        public Nullable<int> ADDRESS_VERIFIED { get; set; }
        public Nullable<int> MEANS_OF_VERIFICATION { get; set; }
        public string MEANS_OF_VERI_OTHER { get; set; }
        public Nullable<bool> IS_VERI_SATISFACTORY { get; set; }
        public string DETAIL_IF_NOT_SATISFACTORY { get; set; }
        public Nullable<int> COUNTRY_HOME_REMITTANCE { get; set; }
        public Nullable<int> REAL_BENEFICIARY_ACCOUNT { get; set; }
        public string NAME_OTHER { get; set; }
        public string CNIC_OTHER { get; set; }
        public Nullable<int> RELATIONSHIP_WITH_ACCOUNTHOLDER { get; set; }
        public string RELATIONSHIP_DETAIL_OTHER { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string BENEFICIAL_ADDRESS { get; set; }
        public Nullable<int> BENEFICIAL_NATIONALITY { get; set; }
        public Nullable<int> BENEFICIAL_RESIDENCE { get; set; }
        public string BENEFICIAL_RESIDENCE_DESC { get; set; }
        public Nullable<int> BENEFICIAL_IDENTITY { get; set; }
        public string BENEFICIAL_IDENTITY_EXPIRY { get; set; }
        public Nullable<int> BENEFICIAL_SOURCE_OF_FUND { get; set; }
        public string NODT { get; set; }
        public string PEDT { get; set; }
        public string NOCT { get; set; }
        public string PECT { get; set; }
        public Nullable<int> RAC { get; set; }
        public string RAC_DETAIL { get; set; }
    }
}
