//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYC_BENEFICIAL_ENTITY
    {
        public int ID { get; set; }
        public Nullable<int> BID { get; set; }
        public string NAME { get; set; }
        public string IDENTITY_DOCUMENT { get; set; }
        public string IDENTITY_NUMBER { get; set; }
        public string EXPIRY_DATE { get; set; }
        public string POB { get; set; }
        public string US { get; set; }
        public string OWNERSHIP { get; set; }
    }
}
