//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYC_PURPOSE_OF_AC
    {
        public int ID { get; set; }
        public int BID { get; set; }
        public int PURPOSE_OF_AC { get; set; }
    }
}
