//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYC_SOURCE_OF_FUND
    {
        public int ID { get; set; }
        public int BID { get; set; }
        public int SOURCE_OF_FUND { get; set; }
    }
}
