//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NADRA_INFO
    {
        public long ID { get; set; }
        public string CNIC { get; set; }
        public System.DateTime DATETIME { get; set; }
        public string NAME { get; set; }
        public string FH_NAME { get; set; }
        public string PRESENT_ADDRESS { get; set; }
        public string PERMANENT_ADDRESS { get; set; }
        public string DOB { get; set; }
        public string BIRTH_PLACE { get; set; }
        public string EXPIRYDATE { get; set; }
        public string STATUSCODE { get; set; }
        public string SESSION_ID { get; set; }
        public string PICTURE { get; set; }
        public string FINGER_INDEX { get; set; }
        public string CONTACTNO_PROVIDED { get; set; }
        public Nullable<int> USERID { get; set; }
        public string BRANCH_CODE { get; set; }
        public string CARD_TYPE { get; set; }
    }
}
