//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHO_AUTHORIZED
    {
        public int ID { get; set; }
        public int CIF_NO { get; set; }
        public string REFERENCE_DOCUMENT_NO { get; set; }
        public string REFERENCE_DOCUMENT_DATE { get; set; }
        public Nullable<int> BI_ID { get; set; }
        public string NAME { get; set; }
        public string IDENTITY_NO { get; set; }
    }
}
